# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

shift_right <- function(mat, cols = 1L, fill = 0L) {
    .Call(`_matrixcalc_shift_right`, mat, cols, fill)
}

