# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ludecomposition <- function(L, U, x, n) {
    .Call(`_matrixcalc_ludecomposition`, L, U, x, n)
}

shift_right <- function(mat, cols = 1L, fill = 0L) {
    .Call(`_matrixcalc_shift_right`, mat, cols, fill)
}

stirling <- function(n) {
    .Call(`_matrixcalc_stirling`, n)
}

toeplitz_matrix <- function(n, x) {
    .Call(`_matrixcalc_toeplitz_matrix`, n, x)
}

